# Generated by Django 5.1.4 on 2025-03-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_advocate_advo_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_request',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='case_request',
            name='case_file',
            field=models.FileField(blank=True, null=True, upload_to='case_files/'),
        ),
        migrations.AddField(
            model_name='case_request',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='case_request',
            name='police_station',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='case_request',
            name='user_email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case_request',
            name='user_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
